baseURL = 'https://grand-phoenix-d50fd5.netlify.app'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "paper"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.parser.attribute]
        block = true

[params]
  twitter = 'capnfabs'
